Repository sourcegraph/about, pull requests merged in 2021-03, with the labels that each got.

#2720 the last of the file renaming for "the batchening"
  handbook/engineering/batch-changes/index.md
  handbook/engineering/batch-changes/supporting-batch-changes.md
Labels: team/batchers

#2730 updated various files for the rename: campaigns -> batch changes
  bin/generate_changelog_items.go
  handbook/engineering/batch-changes/CODENOTIFY
  website/src/components/pricing/PricingPlan.tsx
  website/src/pages/customers.tsx
  website/src/pages/index.tsx
  website/src/pages/pricing.tsx
  website/static/_redirects
Labels: team/batchers

#2731 More "campaigns" -> "batch changes" updates
  company/team/index.md
  handbook/communication/company_meeting.md
  handbook/communication/content_guidelines/actionable_language.md
  handbook/communication/content_guidelines/style_and_mechanics.md
  handbook/engineering/code-intelligence/index.md
  handbook/engineering/hiring/software-engineer-frontend.md
  handbook/engineering/releases/patch_release_issue_template.md
  handbook/engineering/releases/release_issue_template.md
  handbook/engineering/search/goals.md
  handbook/engineering/web/code-insights/goals.md
  handbook/engineering/web/code-insights/index.md
  handbook/engineering/web/code-insights/screenshot.svg
  handbook/ops/bizops/onboarding.md
  handbook/product/design/design-and-interaction-guidelines.md
  handbook/sales/common_customer_questions.md
  handbook/sales/onboarding/index.md
  website/src/pages/customers.tsx
  website/src/pages/index.tsx
Labels: team/batchers

#2745 Final[*] "campaign" -> "batch change" renaming for the About pages
  handbook/engineering/batch-changes/goals.md
  handbook/engineering/batch-changes/index.md
  handbook/engineering/batch-changes/onboarding.md
  handbook/engineering/batch-changes/supporting-batch-changes.md
Labels: team/batchers

#2746 update docs links: campaigns -> batch_changes
  blogposts/2020/code-search-turned-code-checker.md
  blogposts/2020/evolution-of-the-precise-code-intel-backend.md
  blogposts/2020/find-and-replace.md
  handbook/ce/onboarding.md
  handbook/engineering/batch-changes/index.md
  handbook/engineering/batch-changes/onboarding.md
  handbook/engineering/batch-changes/supporting-batch-changes.md
  website/src/pages/index.tsx
Labels: team/batchers

#2748 ci: add geojsonhint job
  .github/workflows/build.yml
Labels: handbook

#2754 capitalize Batch Changes
  company/goals/index.md
  handbook/ce/customer-support-onboarding.md
  handbook/engineering/batch-changes/index.md
  handbook/engineering/eng_org.md
  handbook/engineering/leadership/index.md
  handbook/index.md
  handbook/marketing/messaging.md
  handbook/product/index.md
  handbook/product/roadmap.md
Labels: team/batchers

#2756 Add initial Director of Engineering responsibilities
  handbook/engineering/roles.md
Labels: merge-on-all-approve

#2760 update links to new batch changes demo video
  website/src/pages/customers.tsx
  website/src/pages/index.tsx
Labels: team/batchers

#2527 Workspaces of Sourcegraph blogpost
  blogposts/2021/workspaces-of-sourcegraph.md
  website/static/blog/Workspaces-of-Sourcegraph-Final-compressed.jpg
Labels: blog

#2747 handbook: add doc restart playbook
  handbook/engineering/deployments/instances.md
  handbook/engineering/deployments/kubernetes.md
  handbook/engineering/deployments/playbooks.md
Labels: handbook

#2780 handbook: Update the Extensibility team page
  handbook/engineering/web/extensibility/index.md
Labels: merge-on-all-approve

#2677 Update distribution goals
  handbook/engineering/distribution/goals.md
Labels: team/distribution

#2800 Add more reading material for frontend engineers
  handbook/engineering/onboarding/software-engineer-onboarding.md
Labels: handbook, merge-on-any-approve

#2806 Add Vova to the team page
  company/team/index.md
  company/team/locations.geojson
Labels: handbook

#2826 handbook: Add `Getting cross-team feedback on RFC` section
  handbook/engineering/web/frontend-platform/index.md
Labels: Wildcard DS, handbook

#2773 Adding Developer Education page and link
  handbook/marketing/education.md
  handbook/marketing/index.md
Labels: handbook

#2837 Batchers page updates
  handbook/engineering/batch-changes/index.md
Labels: team/batchers
