Repository sourcegraph/about, pull requests merged in 2021-02, with the labels that each got.

#2460 Add information on how we monitor work progress
  handbook/engineering/web/index.md
Labels: merge-on-any-approve

#2501 Provide clarity on Brex card purchase receipts
  handbook/ops/finance/payables.md
Labels: merge-on-any-approve

#2459 Add the web team's code reviews process
  handbook/engineering/web/index.md
Labels: merge-on-all-approve

#2557 Change web team PM listings to reflect Joel's scope
  handbook/engineering/web/index.md
Labels: merge-on-any-approve

#2608 Add Valery to the team page
  company/team/index.md
Labels: handbook

#2634 Link "Submitting an invoice" to "General onboarding"
  handbook/people-ops/onboarding/general_onboarding.md
Labels: handbook
