Repository sourcegraph/about, pull requests merged in 2022-10, with the labels that each got.

#5821 fix image dimensions
  src/components/CaseStudies/CaseStudyCard.tsx
Labels: team/content-platform, bug fix

#5823 Add git vs perforce blog post
  content/blogposts/2022/git-vs-perforce.md
Labels: about-blog

#5827 Host Dev velocity vs code security pdf
  public/guides/developer-velocity-vs-code-security.pdf
Labels: team/content-platform, marketing-request

#5832 New 4.0 launch twitch video id
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5829 Fix formatting h/t Twarit
  content/blogposts/2022/git-vs-perforce.md
Labels: about-blog

#5825 Remove 4.0 launch banner
  public/sourcegraph/sourcegraph-4.0-white.svg
  src/pages/home/_Banner.tsx
  src/pages/home/index.tsx
Labels: team/content-platform, marketing-request

#5842 Host PDF for DevOps teams
  public/guides/devops-data-driven-relationships-with-codebases.pdf
Labels: team/content-platform

#5845 New resource hub content
  src/components/Resources/resourceItems.ts
Labels: team/content-platform, marketing-request

#5847 Pricing: Xxs Screen tables
  src/components/Pricing/PricingPlan.tsx
  src/components/Pricing/PricingPlanFeature.tsx
  src/pages/pricing.tsx
Labels: team/content-platform

#5851 Batch change: text-muted => tailwind theme
  src/components/Blockquote.tsx
  src/components/Blog/PodcastListItem.tsx
  src/components/Blog/ReleasePost.tsx
  src/components/GatedResourceLayout.tsx
  src/components/Pricing/PricingPlanProperty.tsx
  src/pages/2022-gartner-cool-vendors-in-software-engineering.tsx
Labels: team/content-platform, TW migration

#5856 Add # of engineers back to homepage
  src/pages/home/_Hero.tsx
Labels: team/content-platform

#5860 Optimize images
  content/blogposts/2022/git-vs-perforce.md
Labels: about-blog

#5863 Cta changes product pages
  src/components/Hero.tsx
  src/pages/batch-changes.tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
Labels: team/growth-marketing

#5876 Promote Get trial CTA more & new blog post
  .tool-versions
  content/blogposts/2022/search-tidbits-episode-1.md
  src/components/GatedResourceLayout.tsx
  src/components/Resources/resourceItems.ts
  src/data/breakpoints.ts
  src/pages/accelerate-dev-onboarding.tsx
  src/pages/case-studies/codecov-uses-sourcegraph-to-resolve-incidents-faster.tsx
  src/pages/case-studies/hashicorp-uses-sourcegraph-to-streamline-cross-repository-code-search.tsx
  src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
  src/pages/code-intelligence-platform.tsx
  src/pages/code-search.tsx
  src/pages/fixing-vulnerabilities.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/code-security.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/index.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
Labels: team/growth-marketing

#5878 Host security exhibit pdf
  public/security-exhibit.pdf
Labels: team/growth-marketing

#5879 Add episode 3.6 of the podcast
  content/podcast/3.6.md
Labels: about-blog

#5883 blogpost: migrating from monaco to codemirror
  content/blogposts/2022/migrating-monaco-codemirror.md
Labels: about-blog

#5882 CtaSection updates across About
  src/components/CaseStudies/CaseStudyLayout.tsx
  src/components/CaseStudies/NewCaseStudyLayout.tsx
  src/components/CtaSection.tsx
  src/components/CtaSection/illustration.svg
  src/components/CtaSection/index.tsx
  src/pages/batch-changes.tsx
  src/pages/better-dev-onboarding.tsx
  src/pages/blog/[...slug].tsx
  src/pages/case-studies/index.tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
  src/pages/home/_Hero.tsx
  src/pages/home/index.tsx
  src/pages/pricing.tsx
  src/pages/resources.tsx
  src/pages/shift-left-the-good-parts.tsx
  src/pages/sourcegraph-4.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/code-security.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/videos/product-tour.tsx
  src/util/index.ts
  src/util/plausible.ts
  tailwind.config.js
Labels: marketing, analytics, enhancement, DLS, team/growth-marketing, UX

#5887 Jd/codemirror-fixes
  content/blogposts/2022/migrating-monaco-codemirror.md
Labels: about-blog

#5892 Swap GE logo for Redfin
  public/external-logos/general-electric-logo.svg
  public/external-logos/redfin-logo.svg
  src/components/CustomerLogos.tsx
Labels: team/growth-marketing
