Repository sourcegraph/about, pull requests merged in 2022-04, with the labels that each got.

#5213 Add review section to Careers page
  website/src/components/CustomCarousel.tsx
  website/src/components/QuoteCarousel/index.tsx
  website/src/css/_spacing.scss
  website/src/pages/accelerate-dev-onboarding.tsx
  website/src/pages/demo.tsx
  website/src/pages/fixing-vulnerabilities.tsx
  website/src/pages/jobs.tsx
  website/src/pages/use-cases/onboarding.tsx
  website/src/pages/use-cases/vulnerabilities.tsx
  website/static/ArrowLeft.svg
  website/static/ArrowRight.svg
  website/static/careers/1-Zoom.png
  website/static/careers/2-Zoom.png
  website/static/careers/3-Zoom.png
  website/static/careers/4-Zoom.png
  website/static/careers/5-Zoom.png
  website/static/careers/6-Zoom.png
  website/static/careers/7-Zoom.png
  website/static/careers/8-Zoom.png
  website/static/careers/review1.png
  website/static/careers/review2.png
  website/static/careers/review3.png
  website/static/careers/review4.png
  website/static/careers/review5.png
  website/static/careers/review6.png
Labels: team/content-platform, marketing-request

#4960 Update maternity leave post with keyword
  blogposts/2018/how-to-support-your-employee-through-pregnancy-maternity-leave-and-the.md
Labels: about-blog

#5253 Update autolink headers
  docs/privacy.md
  website/gatsby-config.js
Labels: team/content-platform

#5248 Replace Glassdoor Review screenshots with QuoteCarousel
  website/src/components/Blockquote.tsx
  website/src/components/QuoteCarousel/index.tsx
  website/src/css/pages/_jobs.scss
  website/src/pages/jobs.tsx
  website/static/careers/1-Zoom.png
  website/static/careers/2-Zoom.png
  website/static/careers/3-Zoom.png
  website/static/careers/4-Zoom.png
  website/static/careers/5-Zoom.png
  website/static/careers/6-Zoom.png
  website/static/careers/7-Zoom.png
  website/static/careers/8-Zoom.png
  website/static/careers/Culture_8.png
  website/static/careers/culture1.png
  website/static/careers/culture2.png
  website/static/careers/culture3.png
  website/static/careers/culture4.png
  website/static/careers/culture5.png
  website/static/careers/culture6.jpg
  website/static/careers/culture6.png
  website/static/careers/culture7.png
  website/static/careers/review1.png
  website/static/careers/review2.png
  website/static/careers/review3.png
  website/static/careers/review4.png
  website/static/careers/review5.png
  website/static/careers/review6.png
Labels: team/content-platform

#5258 Colour and Gradient Improvements
  website/src/components/Header.tsx
  website/src/components/IconItem.tsx
  website/src/components/Install/install.module.scss
  website/src/components/Jumbotron.tsx
  website/src/components/QuoteCarousel/index.tsx
  website/src/components/TestimonialCarousel.tsx
  website/src/components/blog/LinkPost.tsx
  website/src/components/content/ContentSection.tsx
  website/src/components/product/OpenSourcePrivacyFeatureItem.tsx
  website/src/css/_colors.scss
  website/src/css/_gradients.scss
  website/src/css/_typography.scss
  website/src/css/components/_ComparisonTable.scss
  website/src/css/components/_CustomCarousel.scss
  website/src/css/components/_Header.scss
  website/src/css/components/_IconItem.scss
  website/src/css/components/_LeadershipSection.scss
  website/src/css/components/_SelfHostedSection.scss
  website/src/css/components/_TemplateCodeBlock.scss
  website/src/css/components/blog/_BlogPost.scss
  website/src/css/components/blog/_PostsList.scss
  website/src/css/components/product/_GitLabIntegrationSection.scss
  website/src/css/pages/__white_papers.scss
  website/src/css/pages/_about.scss
  website/src/css/pages/_batch-changes.scss
  website/src/css/pages/_code-insights.scss
  website/src/css/pages/_content.scss
  website/src/css/pages/_jobs.scss
  website/src/css/pages/_podcast.scss
  website/src/css/pages/_sales.scss
  website/src/css/pages/_universal-code-search.scss
  website/src/css/pages/product/_code-change-management.scss
  website/src/css/styles.scss
  website/src/css/templates/_PostTemplate.scss
  website/src/pages/accelerate-dev-onboarding.tsx
  website/src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
  website/src/pages/cloud-beta.tsx
  website/src/pages/code-insights.tsx
  website/src/pages/fixing-vulnerabilities.tsx
  website/src/pages/get-started/getStarted.module.scss
  website/src/pages/get-started/self-hosted.tsx
  website/src/pages/guides/continuous-developer-onboarding/index.module.scss
  website/src/pages/index.tsx
  website/src/pages/jobs.tsx
  website/src/pages/use-cases/onboarding.tsx
  website/src/pages/use-cases/useCases.module.scss
  website/src/pages/use-cases/vulnerabilities.tsx
Labels: team/content-platform

#5262 Update title based on Justin's feedback
  blogposts/2021/tackling-the-long-tail.md
Labels: about-blog

#5260 Improve HubSpot/ChiliPiper forms with new hook implementation
  website/src/components/HubSpot.tsx
  website/src/pages/contact/product-specialist.tsx
  website/src/pages/contact/request-batch-changes-demo.tsx
  website/src/pages/contact/request-code-change-management-demo.tsx
  website/src/pages/contact/request-code-insights-demo.tsx
  website/src/pages/contact/request-demo.tsx
  website/src/pages/contact/request-info.tsx
  website/src/pages/contact/request-trial.tsx
  website/src/pages/resources/universal-code-search-ebook.tsx
Labels: team/content-platform

#5267 Add link to Nutanix case study
  blogposts/2022/third-party-vulnerabilities-process.md
Labels: about-blog

#5273 Add blog post proposal template
  .github/ISSUE_TEMPLATES/blog_post.md
Labels: about-blog

#5279 Remove CTAs, add update to Cloud private beta
  blogposts/2021/sourcegraph-cloud-teams-beta.md
Labels: about-blog

#5283 Edits to Fig post
  blogposts/2022/why-fig-autocomplete-is-awesome.md
Labels: about-blog

#5268 Embed demo form to Code-Insights pg
  website/src/pages/code-insights.tsx
Labels: team/content-platform, marketing-request

#5270 Notebooks/code search updates
  website/src/components/Install/index.tsx
  website/src/pages/code-search.tsx
Labels: team/content-platform, marketing-request

#5295 Create Notebooks technical launch post
  blogposts/2022/notebooks-ci.md
Labels: about-blog

#5305 Add og url and image secure url for meta
  website/src/components/Layout.tsx
Labels: enhancement, team/content-platform

#5308 Bug Fix for "Deploy locally" CTA button on /code-search
  website/src/pages/code-search.tsx
Labels: bug, team/content-platform, added-mid-sprint

#5291 Fix HubSpot form loading
  website/src/css/_colors.scss
  website/src/hooks/hubSpot.ts
Labels: bug, team/content-platform

#5303 Create monoliths to microservices post
  blogposts/2022/monolith-microservices.md
Labels: about-blog

#5288 remove cloud-beta, redirect to home, copy updates to get-started
  netlify.toml
  website/src/pages/cloud-beta.tsx
  website/src/pages/get-started/cloud.tsx
  website/src/pages/get-started/index.tsx
Labels: team/content-platform, marketing-request, added-mid-sprint
