Repository sourcegraph/about, pull requests merged in 2022-05, with the labels that each got.

#5259 Incident response use case
  website/src/components/CustomCarousel.tsx
  website/src/components/QuoteCarousel/index.tsx
  website/src/css/_spacing.scss
  website/src/pages/use-cases/incident-response.tsx
  website/src/pages/use-cases/index.tsx
  website/src/pages/use-cases/onboarding.tsx
  website/src/pages/use-cases/vulnerabilities.tsx
Labels: team/content-platform, marketing-request

#5309 Update HubSpot forms
  website/src/hooks/chiliPiper.ts
  website/src/hooks/hubSpot.ts
  website/src/hooks/index.ts
  website/src/pages/accelerate-dev-onboarding.tsx
  website/src/pages/code-insights.tsx
  website/src/pages/contact/product-specialist.tsx
  website/src/pages/contact/request-batch-changes-demo.tsx
  website/src/pages/contact/request-code-change-management-demo.tsx
  website/src/pages/contact/request-code-insights-demo.tsx
  website/src/pages/contact/request-demo.tsx
  website/src/pages/contact/request-info.tsx
  website/src/pages/contact/request-trial.tsx
  website/src/pages/demo.tsx
  website/src/pages/fixing-vulnerabilities.tsx
  website/src/pages/guides/continuous-developer-onboarding/index.tsx
  website/src/pages/partner-podcast.tsx
  website/src/pages/resources/universal-code-search-ebook.tsx
Labels: bug, team/content-platform

#5324 Bugfix/Blog post link to author url
  website/src/components/blog/BlogPost.tsx
Labels: bug, team/content-platform

#5330 eBook Copy Correction
  website/src/pages/guides/dev-onboarding-how-is-it-unique/index.tsx
Labels: team/content-platform, added-mid-sprint

#5271 Use Case/ Code Reuse
  website/src/components/BlogListItem.tsx
  website/src/components/CustomCarousel.tsx
  website/src/components/Layout.tsx
  website/src/components/ThreeUpText.tsx
  website/src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
  website/src/pages/code-insights.tsx
  website/src/pages/partner-podcast.tsx
  website/src/pages/use-cases/code-health.tsx
  website/src/pages/use-cases/code-reuse.tsx
  website/src/pages/use-cases/incident-response.tsx
  website/src/pages/use-cases/index.tsx
  website/src/pages/use-cases/onboarding.tsx
  website/src/pages/use-cases/vulnerabilities.tsx
Labels: team/content-platform, marketing-request

#5335 Use Case: Code Reuse thumbnail & copy changes
  website/src/pages/use-cases/code-reuse.tsx
Labels: team/content-platform, marketing-request

#5338 Update Use Case blog list items
  website/src/pages/use-cases/code-health.tsx
  website/src/pages/use-cases/incident-response.tsx
Labels: team/content-platform

#5340 Homepage Updates
  website/src/components/CustomerLogos.tsx
  website/src/components/Install/index.tsx
  website/src/components/SelfHostedSection.tsx
  website/src/pages/get-started/self-hosted.tsx
  website/src/pages/home/_Features.tsx
  website/src/pages/home/_Hero.tsx
  website/src/pages/home/_UseCases.tsx
  website/src/pages/use-cases/index.tsx
  website/src/tracking.ts
  website/static/external-logos/adidas-running-logo.svg
  website/static/external-logos/adidas-runtastic-sq-logo.svg
  website/static/external-logos/canva-logo.svg
Labels: team/content-platform

#5339 swap ctas on code search page header
  website/src/pages/code-search.tsx
Labels: team/content-platform, marketing-request

#5322 Create 5 thoughts of dev productivity post
  blogposts/2022/developer-productivity.md
Labels: about-blog

#5297 Incident response use case /non-blocking feedback
  website/src/pages/use-cases/incident-response.tsx
Labels: team/content-platform, marketing-request

#5344 Nutanix Webinar page
  website/src/components/content/CaseStudyPage.tsx
  website/src/components/webinars/WebinarLayout.module.scss
  website/src/components/webinars/WebinarLayout.tsx
  website/src/css/components/_Footer.scss
  website/src/css/components/_Header.scss
  website/src/css/styles.scss
  website/src/hooks/hubSpot.ts
  website/src/pages/webinars/preparing-for-the-next-log4j.tsx
  website/static/bg-code-mars-mobile.png
  website/static/bg-code-mars.png
  website/static/case-studies/jon-kohler.png
  website/static/case-studies/mike-mclaughlin.png
  website/static/sourcegraph/sourcegraph-mark.png
  website/static/sourcegraph/sourcegraph-mark.svg
Labels: team/content-platform, marketing-request

#5349 Webinar/Code Insights
  website/src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
  website/static/staff/joel-kwartler.png
  website/static/staff/shawn-king.png
Labels: team/content-platform, marketing-request

#5354 a11y issue template
  .github/ISSUE_TEMPLATE/accessibility_issue.yaml
Labels: accessibility

#5366 Update terms links
  content/terms/archives/cloud/2022-02-09.md
  content/terms/archives/self-hosted/2021-08-25.md
  content/terms/archives/self-hosted/2021-10-11.md
  content/terms/archives/self-hosted/2022-02-10.md
  content/terms/archives/subprocessors/2021-12-03.md
  content/terms/cloud.md
  content/terms/privacy.md
  content/terms/self-hosted.md
  content/terms/subprocessors.md
Labels: bug, team/content-platform, added-mid-sprint

#5367 Format publishDate for release posts
  src/components/Blog/ReleasePost.tsx
Labels: team/content-platform, added-mid-sprint

#5388 Changelog redirect
  netlify.toml
Labels: team/content-platform, post-merge

#5392 Add code insights back to mobile nav
  src/components/Layout/Header.tsx
Labels: bug, team/content-platform, added-mid-sprint

#5385 Add No Secrets! blog post
  content/blogposts/2022/no-secrets.md
Labels: about-blog

#5386 Script loading strategies, HubSpot hook refactor, and Triblio script fix
  src/hooks/hubSpot.ts
  src/pages/_app.tsx
Labels: bug, enhancement, team/content-platform

#5387 /code-search updated CTA buttons
  src/components/Install/index.tsx
  src/components/SelfHostedSection.tsx
  src/pages/batch-changes.tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
  src/pages/home/_Features.tsx
  src/pages/home/_Hero.tsx
  src/pages/home/_UseCases.tsx
  src/pages/pricing.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/index.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/use-cases/vulnerabilities.tsx
Labels: team/content-platform, added-mid-sprint, post-merge

#5394 Remove No Secrets post
  content/blogposts/2022/no-secrets.md
Labels: about-blog

#4940 Add CTO title
  content/podcast/2.8.md
Labels: podcast

#5397 HubSpot form loading, Clearbit, and automated build/linting workflow
  .github/pull_request_template.md
  .github/workflows/lintAndBuild.yml
  src/hooks/hubSpot.ts
  src/pages/_app.tsx
Labels: bug, team/content-platform, added-mid-sprint

#5398 Add new version of No Secrets post
  content/blogposts/2022/no-secrets-v2.md
Labels: about-blog

#5406 Bug fixes for case study and use case pages
  .github/pull_request_template.md
  src/components/Blockquote.tsx
  src/components/CaseStudies/AuthorBio.tsx
  src/pages/guides/fixing-vulnerabilities-less-is-more.tsx
  src/styles/globals.scss
  src/styles/pages/__case_studies.scss
Labels: bug, team/content-platform, added-mid-sprint
