Repository sourcegraph/about, pull requests merged in 2022-06, with the labels that each got.

#5365 Demand-Gen: Dev Onboarding Landing
  public/blog/thumbnails/code-insights-docs.png
  public/blog/thumbnails/continuous-developer-onboarding.png
  src/components/FeatureWalkthrough/animations/batch-changes.mp4
  src/components/FeatureWalkthrough/animations/batch-changes.webm
  src/components/FeatureWalkthrough/animations/code-insights.mp4
  src/components/FeatureWalkthrough/animations/code-insights.webm
  src/components/FeatureWalkthrough/animations/code-intel.mp4
  src/components/FeatureWalkthrough/animations/code-intel.webm
  src/components/FeatureWalkthrough/animations/code-search.mp4
  src/components/FeatureWalkthrough/animations/code-search.webm
  src/components/FeatureWalkthrough/index.tsx
  src/components/index.ts
  src/pages/better-dev-onboarding.tsx
  src/pages/home/index.tsx
  src/pages/partner-podcast.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/use-cases/vulnerabilities.tsx
Labels: team/content-platform

#5395 Navigation updates, Code Security name change
  netlify.toml
  src/components/Actions/ContactPresalesSupportAction.tsx
  src/components/Blog/ReleasePost.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/Header/DesktopNav.tsx
  src/components/Layout/Header/MobileNav.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/navLinks.ts
  src/components/Layout/index.tsx
  src/pages/batch-changes.tsx
  src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
  src/pages/contact/index.tsx
  src/pages/contact/product-specialist.tsx
  src/pages/home/_UseCases.tsx
  src/pages/pricing.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/code-security.tsx
  src/pages/use-cases/index.tsx
  src/styles/components/_Header.scss
Labels: team/content-platform

#5420 Follow up for nav updates
  src/components/Layout/Footer.tsx
Labels: added-mid-sprint

#5393 Gated Pg/ Gartner report
  public/external-logos/gartner-cool-vendor-2022.png
  src/components/GatedResourceLayout/index.tsx
  src/pages/2022-gartner-cool-vendors-in-software-engineering.tsx
  src/pages/guides/optimizing-developer-onboarding.tsx
  src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
  src/pages/webinars/preparing-for-the-next-log4j.tsx
Labels: team/content-platform, marketing-request

#5429 Replace mentions of Slack with Discord
  src/pages/community.tsx
Labels: high priority

#5434 Client logo updates
  public/external-logos/databricks-logo.svg
  public/external-logos/paypal-logo.svg
  src/components/CustomerLogos.tsx
Labels: team/content-platform, marketing-request

#5436 Platform Positioning Copy
  src/pages/2022-gartner-cool-vendors-in-software-engineering.tsx
  src/pages/batch-changes.tsx
  src/pages/case-studies/index.tsx
  src/pages/code-search.tsx
  src/pages/community.tsx
  src/pages/pricing.tsx
  src/pages/use-cases/index.tsx
Labels: team/content-platform

#5440 Video thumbnail meta for social sharing
  content/podcast/0.md
  content/podcast/1.md
  content/podcast/10.md
  content/podcast/11.md
  content/podcast/2.10.md
  content/podcast/2.11.md
  content/podcast/2.12.md
  content/podcast/2.13.md
  content/podcast/2.14.md
  content/podcast/2.15.md
  content/podcast/2.17.md
  content/podcast/2.18.md
  content/podcast/2.19.md
  content/podcast/2.5.md
  content/podcast/2.6.md
  content/podcast/2.7-2.md
  content/podcast/2.7.md
  content/podcast/2.8.md
  content/podcast/2.9.md
  content/podcast/2.md
  content/podcast/3.1.md
  content/podcast/3.2.md
  content/podcast/3.md
  content/podcast/4.md
  content/podcast/5.md
  content/podcast/6.md
  content/podcast/7.md
  content/podcast/8.md
  content/podcast/9.md
  public/meta/sourcegraph-social.png
  src/components/Layout/index.tsx
  src/interfaces/posts.ts
  src/pages/blog/[...slug].tsx
  src/pages/podcast/[...slug].tsx
  src/pages/press-release/[...slug].tsx
Labels: about-blog, team/content-platform, podcast, analytics, release, improvement

#5437 SCIP & SCIP-TypeScript Blogposts
  content/blogposts/2022/announcing-scip-typescript.md
  content/blogposts/2022/announcing-scip.md
Labels: team/content-platform

#5458 Fix table scrolling gray bar on SCIP-TS blogpost
  content/blogposts/2022/announcing-scip-typescript.md
Labels: team/content-platform, bug fix

#5459 Follow up for video meta
  src/components/Layout/index.tsx
Labels: team/content-platform, podcast, bug fix, improvement

#5463 Add Justin's bio to fig post
  content/blogposts/2022/no-secrets-v2.md
  content/blogposts/2022/why-fig-autocomplete-is-awesome.md
Labels: about-blog

#5450 Webinar Recording pg: Nutanix
  src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
  src/pages/webinars/preparing-for-the-next-log4j.tsx
Labels: team/content-platform, marketing-request

#5468 Hotfix/Webinar spacing
  src/components/GatedResourceLayout/index.tsx
  src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
  src/pages/webinars/preparing-for-the-next-log4j.tsx
Labels: team/content-platform

#5444 Reorder sections on Code Insights
  src/components/Carousels/CustomCarousel.tsx
  src/pages/code-insights.tsx
  src/styles/pages/_code-insights.scss
Labels: team/content-platform

#5474 Hotfix/Webinar spacing
  src/components/GatedResourceLayout/index.tsx
Labels: team/content-platform, marketing-request

#5475 Collocated home redirect trailing slash fix
  netlify.toml
Labels: team/content-platform, bug fix

#5456 Redesign old Guide pages
  public/guides/dev-onboarding-unique/hero-mobile.png
  public/guides/dev-onboarding-unique/hero.png
  public/guides/dev-onboarding/hero-mobile.png
  public/guides/dev-onboarding/hero.png
  public/guides/dev-onboarding/thumbnail.png
  public/guides/sg-continuous-developer-onboarding.pdf
  public/guides/sg-dev-onboarding-what-makes-it-unique.pdf
  src/components/GatedResourceLayout/index.tsx
  src/pages/guides/continuous-developer-onboarding.tsx
  src/pages/guides/continuous-developer-onboarding/index.module.scss
  src/pages/guides/continuous-developer-onboarding/index.tsx
  src/pages/guides/dev-onboarding-how-is-it-unique.tsx
  src/pages/guides/dev-onboarding-how-is-it-unique/index.module.scss
  src/pages/guides/dev-onboarding-how-is-it-unique/index.tsx
Labels: team/content-platform

#5449 Update meta on Case Studies and Use Cases
  src/pages/case-studies/index.tsx
  src/pages/use-cases/index.tsx
Labels: team/content-platform

#5494 E2E test coverage for GA, GTM, and third party scripts
  .github/workflows/tests.yml
  .gitignore
  README.md
  cypress.config.ts
  cypress/e2e/scripts.test.ts
  cypress/plugins/index.js
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package.json
  src/pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: team/content-platform, analytics, testing

#5493 Shift Left Blogpost
  content/blogposts/2022/announcing-scip.md
  content/blogposts/2022/shift-left-wtf-does-it-mean.md
  src/components/Blog/PostLayout.tsx
  src/components/Video.tsx
  src/components/YouTube.tsx
  src/pages/accelerate-dev-onboarding.tsx
  src/pages/batch-changes.tsx
  src/pages/blog/[...slug].tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
  src/pages/community.tsx
  src/pages/demo.tsx
  src/pages/fixing-vulnerabilities.tsx
  src/pages/podcast/[...slug].tsx
  src/pages/press/[...slug].tsx
  src/styles/components/blog/_BlogPost.scss
Labels: about-blog, team/content-platform

#5499 Fix Shift Left Video
  content/blogposts/2022/shift-left-wtf-does-it-mean.md
  src/components/Video.tsx
Labels: team/content-platform, bug fix

#5504 Update about pg staff
  public/staff/avatar-beyang.jpg
  public/staff/avatar-beyang.png
  public/staff/avatar-carly.jpg
  public/staff/avatar-carly.png
  public/staff/avatar-christina.jpg
  public/staff/avatar-christina.png
  public/staff/avatar-kacie.jpg
  public/staff/avatar-nick.jpg
  public/staff/avatar-nick.png
  public/staff/avatar-quinn.jpg
  public/staff/avatar-quinn.png
  src/components/LeadershipSection.tsx
Labels: team/content-platform

#5482 Update Open Graph Images
  content/blogposts/2020/series-c-with-sequoia.md
  content/blogposts/2021/introducing-batch-changes.md
  content/blogposts/2021/why-were-friends-not-competitors-with-code-hosts.md
  public/external-logos/cern-name-reverse-logo.svg
  public/meta/sourcegraph-social.png
  src/components/Blog/PostListItem.tsx
  src/components/Layout/index.tsx
  src/pages/case-studies/cern-reduces-technical-debt.tsx
  src/pages/case-studies/convoy-improved-on-boarding.tsx
  src/pages/case-studies/criteo-tackles-big-code.tsx
  src/pages/case-studies/f5-streamlines-collaboration-globally.tsx
  src/pages/case-studies/quantcast-large-scale-refactoring.tsx
  src/pages/case-studies/sofi-moves-fast-on-hundreds-of-microservices.tsx
  src/pages/case-studies/we-are-thorn.tsx
  src/pages/dev-tools-quiz.tsx
Labels: team/content-platform

#5511 Add author
  content/blogposts/2022/no-secrets-v2.md
Labels: about-blog

#5510 Missing special blogposts & redirects
  content/blogposts/go/liveblogging-gophercon-2019.md
  netlify.toml
Labels: team/content-platform, post-merge, bug fix, high priority

#5520 Syntax Highlighting
  additional.d.ts
  content/blogposts/2021/java-scala-kotlin-code-intelligence.md
  content/blogposts/2022/css-modules-migration.md
  content/blogposts/2022/introducing-migrator-service.md
  content/blogposts/go/gophercon-2018-how-to-write-a-parser-in-go.md
  package.json
  src/lib/loadMarkdown.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/code-insights.tsx
  src/styles/components/_PrismTheme.scss
  src/styles/components/blog/_LinkPost.scss
  src/styles/components/blog/_ReleasePost.scss
  src/styles/globals.scss
  src/styles/templates/_PostTemplate.scss
  yarn.lock
Labels: team/content-platform, improvement

#5527 Update demo video
  src/pages/demo.tsx
Labels: team/content-platform, marketing-request, medium priority

#5525 Add new blog post: How our OSPO uses Batch Changes...
  content/blogposts/2022/announcing-scip-typescript.md
  content/blogposts/2022/batch-changes-ospo.md
Labels: about-blog

#5533 Jd/batch changes typo
  content/blogposts/2022/batch-changes-ospo.md
Labels: about-blog

#5524 Audit & Add missing languages for highlighting
  content/blogposts/2016/announcing-checkup-simple-self-hosted-health-checks.md
  content/blogposts/2016/google-i-o-talk-building-sourcegraph.md
  content/blogposts/2016/why-we-open-sourced-our-uptime-monitoring-system.md
  content/blogposts/2017/great-code-search-for-aws-codecommit.md
  content/blogposts/2017/how-caddy-auto-detects-https-interception.md
  content/blogposts/2018/code-intelligence-in-vim.md
  content/blogposts/2018/the-pain-that-minimal-version-selection-solves.md
  content/blogposts/2019/announcing-sourcegraph-3.5.md
  content/blogposts/2019/lsif-indexer.md
  content/blogposts/2020/announcing-sourcegraph-3.15.md
  content/blogposts/2020/evolution-of-the-precise-code-intel-backend.md
  content/blogposts/2020/find-and-replace.md
  content/blogposts/2020/performance-improvements-in-precise-code-intel.md
  content/blogposts/2021/eliminating-secrets-from-codebase.md
  content/blogposts/2021/nine-circles-of-dependency-hell.md
  content/blogposts/2021/postgres-text-search-balancing-query-time-and-relevancy.md
  content/blogposts/2021/postgres-version-update.md
  content/blogposts/2021/release-3.28.md
  content/blogposts/2022/sourcegraph-extension-for-vs-code.md
  content/blogposts/go/a-go-guide-to-syscalls.md
  content/blogposts/go/advanced-testing-in-go.md
  content/blogposts/go/an-introduction-to-go-tool-trace-rhys-hiltner.md
  content/blogposts/go/creating-a-custom-serialization-format.md
  content/blogposts/go/forward-compatible-go-code.md
  content/blogposts/go/generating-better-machine-code-with-ssa.md
  content/blogposts/go/go-at-the-darpa-cyber-grand-challenge-will-hawkins.md
  content/blogposts/go/go-lift.md
  content/blogposts/go/gophercon-2018-allocator-wrestling.md
  content/blogposts/go/gophercon-2018-becoming-a-go-contributor.md
  content/blogposts/go/gophercon-2018-c-l-eye-catching-user-interfaces.md
  content/blogposts/go/gophercon-2018-how-to-write-a-parser-in-go.md
  content/blogposts/go/gophercon-2018-implementing-a-network-protocol-in-go.md
  content/blogposts/go/gophercon-2018-micro-optimizing-go-code.md
  content/blogposts/go/gophercon-2018-rethinking-classical-concurrency-patterns.md
  content/blogposts/go/gophercon-2019-better-x86-assembly-generation-from-go.md
  content/blogposts/go/gophercon-2019-handling-go-errors.md
  content/blogposts/go/gophercon-2019-simple-portable-efficient-graphical-interfaces-in-go.md
  content/blogposts/go/gophercon-2019-tracking-inter-process-dependencies-using-static-analysis.md
  content/blogposts/go/gophercon-2019-two-go-programs-three-different-profiling-techniques-in-50-minutes.md
  content/blogposts/go/idiomatic-go.md
  content/blogposts/go/operability-in-go.md
  content/blogposts/go/runtime-generated-typesafe-and-declarative-pick-any-three.md
  content/blogposts/go/the-functional-design-of-dep-and-package-managers-in-general.md
  content/blogposts/go/the-future-of-go.md
  content/blogposts/go/valuable-lessons-in-over-engineering-the-core-of-kubernetes-kops.md
  content/blogposts/go/writing-a-go-tool-to-parse-and-modify-struct-tags.md
  content/blogposts/graphql/graphql-at-massive-scale-graphql-as-the-glue-in-a-microservice-architecture.md
  content/blogposts/graphql/graphql-at-twitter.md
  content/blogposts/graphql/graphql-client-driven-development.md
  content/blogposts/graphql/graphql-productivity.md
  content/blogposts/graphql/supercharge-your-graphql-development.md
  content/blogposts/strange-loop/strange-loop-2019-complexities-of-color-in-computing.md
  content/terms/archives/cloud/2021-06-25.md
  content/terms/archives/cloud/2021-12-09.md
  content/terms/archives/cloud/2022-02-09.md
  content/terms/cloud.md
Labels: about-blog, team/content-platform, added-mid-sprint, improvement
