Repository sourcegraph/about, pull requests merged in 2022-09, with the labels that each got.

#5706 Case study/ Hashicorp
  public/case-studies/bryce-kallow.png
  public/external-logos/hashicorp-logo.svg
  src/components/Blockquote.tsx
  src/components/CaseStudies/CaseStudyCard.tsx
  src/components/CaseStudies/StaffSpotlight.tsx
  src/components/CaseStudies/UseChallengeSolutionResults.tsx
  src/components/CaseStudies/index.ts
  src/components/CtaSection.tsx
  src/components/ThreeUpText.tsx
  src/components/index.ts
  src/pages/case-studies/codecov-uses-sourcegraph-to-resolve-incidents-faster.tsx
  src/pages/case-studies/hashicorp-uses-sourcegraph-to-streamline-cross-repository-code-search.tsx
  src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
Labels: team/content-platform, marketing-request, medium priority, P2

#5716 Hotfix/ Long form content width & CtaSection text color
  src/components/Background/index.tsx
  src/components/CaseStudies/CaseStudyLayout.tsx
  src/components/ContentSection.tsx
  src/components/CtaSection.tsx
  src/pages/blog/[...slug].tsx
  src/pages/case-studies/cern-reduces-technical-debt.tsx
  src/pages/case-studies/cloudflare-accelerates-debugging-and-improves-security.tsx
  src/pages/case-studies/codecov-uses-sourcegraph-to-resolve-incidents-faster.tsx
  src/pages/case-studies/convoy-improved-on-boarding.tsx
  src/pages/case-studies/criteo-tackles-big-code.tsx
  src/pages/case-studies/f5-streamlines-collaboration-globally.tsx
  src/pages/case-studies/factset-migrates-from-perforce-to-github.tsx
  src/pages/case-studies/hashicorp-uses-sourcegraph-to-streamline-cross-repository-code-search.tsx
  src/pages/case-studies/indeed-accelerates-development-velocity.tsx
  src/pages/case-studies/lyft-monolith-to-microservices.tsx
  src/pages/case-studies/nutanix-fixed-log4j-with-sourcegraph.tsx
  src/pages/case-studies/quantcast-large-scale-refactoring.tsx
  src/pages/case-studies/sofi-moves-fast-on-hundreds-of-microservices.tsx
  src/pages/case-studies/we-are-thorn.tsx
  src/pages/case-studies/workiva-automates-large-scale-code-changes.tsx
Labels: team/content-platform, bug fix

#5721 Patch/ Case study spelling update
  public/case-studies/bryce-kalow.png
  src/pages/case-studies/hashicorp-uses-sourcegraph-to-streamline-cross-repository-code-search.tsx
Labels: team/content-platform

#5725 Sourcegraph 4.0 calendar link update
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5733 Bug Fix: Follow up for anchor linked sections
  src/hooks/index.ts
  src/hooks/scrollToAnchor.ts
  src/pages/_app.tsx
  src/styles/globals.css
Labels: team/content-platform, bug fix

#5735 Update self-hosted terms
  content/terms/self-hosted.md
Labels: team/content-platform

#5736 Update Cloud terms
  content/terms/cloud.md
Labels: legal, team/content-platform

#5669 Resources Page
  src/components/Background/index.tsx
  src/components/Badge.tsx
  src/components/CaseStudies/CaseStudyCard.tsx
  src/components/Hero.tsx
  src/components/Layout/navLinks.tsx
  src/components/Resources/Card.tsx
  src/components/Resources/Filters.tsx
  src/components/Resources/index.ts
  src/components/Resources/resourceItems.ts
  src/components/Resources/useFilters.ts
  src/components/index.ts
  src/pages/resources.tsx
  src/pages/sourcegraph-4.tsx
  src/pages/videos/product-tour.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: team/content-platform, marketing-request, sprint-rollover, improvement

#5740 HubSpot Form styling
  src/styles/components/_HubSpotForms.scss
  src/styles/globals.scss
Labels: team/content-platform

#5742 UTM Source for demo CTAs on blog pages
  src/components/Layout/Header/DesktopNav.tsx
  src/pages/blog/[...slug].tsx
Labels: team/content-platform

#5744 Update Security page
  content/terms/security.md
  src/pages/terms/[...slug].tsx
Labels: team/content-platform

#5745 New blog components for 4.0 launch
  content/blogposts/blog-post-starter-pack.md
  src/components/Badge.tsx
  src/components/Blog/PostLayout.tsx
  src/components/Blog/ReleasePost.tsx
  src/components/Figure.tsx
  src/components/Resources/Card.tsx
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5743 Script loading strategies
  cypress/e2e/scripts.test.ts
  next.config.js
  package.json
  src/components/Blockquote.tsx
  src/components/Blog/PostListItem.tsx
  src/components/Blog/PostsListPage.tsx
  src/components/Carousels/TabCarousel.tsx
  src/components/CodeInsights/CodeInsightsExamples.tsx
  src/components/CoreFeatures.tsx
  src/components/Layout/index.tsx
  src/components/Layout/navLinks.tsx
  src/components/Pricing/PricingPlan.tsx
  src/components/Pricing/PricingPlanProperty.tsx
  src/components/TemplateCodeBlock.tsx
  src/hooks/carousel.ts
  src/interfaces/posts.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  yarn.lock
Labels: team/content-platform, analytics

#5750 Universal and GA4 analytics
  src/pages/_document.tsx
Labels: analytics

#5754 Remove async and manual gtag script
  src/pages/_document.tsx
Labels: team/content-platform, bug fix, analytics

#5753 OpenInNewIcon for blog videos & standalone links
  content/blogposts/blog-post-starter-pack.md
  content/terms/security.md
  src/components/Blog/PostLayout.tsx
  src/components/Blog/ReleasePost.tsx
  src/components/Video.tsx
Labels: about-blog, team/content-platform, marketing-request

#5761 Next.js script recommendations
  cypress/e2e/scripts.test.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: team/content-platform, bug fix, analytics, improvement

#5759 Badge links a11y & Release post 4.0 footer update
  content/blogposts/blog-post-starter-pack.md
  content/terms/security.md
  next-sitemap.config.js
  src/components/Badge.tsx
  src/components/Blog/ReleasePost.tsx
  src/components/ContentSection.tsx
  src/components/Figure.tsx
  src/components/Video.tsx
  src/pages/case-studies/cern-reduces-technical-debt.tsx
  src/pages/case-studies/cloudflare-accelerates-debugging-and-improves-security.tsx
  src/pages/case-studies/convoy-improved-on-boarding.tsx
  src/pages/case-studies/criteo-tackles-big-code.tsx
  src/pages/case-studies/f5-streamlines-collaboration-globally.tsx
  src/pages/case-studies/factset-migrates-from-perforce-to-github.tsx
  src/pages/case-studies/indeed-accelerates-development-velocity.tsx
  src/pages/case-studies/lyft-monolith-to-microservices.tsx
  src/pages/case-studies/quantcast-large-scale-refactoring.tsx
  src/pages/case-studies/sofi-moves-fast-on-hundreds-of-microservices.tsx
  src/pages/case-studies/we-are-thorn.tsx
  src/pages/case-studies/workiva-automates-large-scale-code-changes.tsx
  src/styles/components/blog/_ReleasePost.scss
Labels: about-blog, team/content-platform

#5769 DLS Footer and banner/nav bug fix
  src/components/Layout/Footer.tsx
  src/components/Layout/navLinks.tsx
  src/styles/components/_Header.scss
Labels: team/content-platform, added-mid-sprint, bug fix, improvement, DLS

#5772 Redirect DPA to security dashboard
  netlify.toml
  public/dpa.pdf
Labels: legal, team/content-platform

#5762 4.0/CTA update
  src/components/CaseStudies/CaseStudyLayout.tsx
  src/components/CaseStudies/NewCaseStudyLayout.tsx
  src/components/CtaSection.tsx
  src/components/Layout/Header/DesktopNav.tsx
  src/components/Layout/Header/MobileNav.tsx
  src/components/WhitePaperPage.tsx
  src/pages/batch-changes.tsx
  src/pages/better-dev-onboarding.tsx
  src/pages/blog/[...slug].tsx
  src/pages/case-studies/index.tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
  src/pages/home/index.tsx
  src/pages/partner-podcast.tsx
  src/pages/pricing.tsx
  src/pages/resources.tsx
  src/pages/shift-left-the-good-parts.tsx
  src/pages/support.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/code-security.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/index.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/videos/product-tour.tsx
Labels: team/content-platform

#5755 Home page - 4.0 updates
  public/sourcegraph/sourcegraph-4-starship.svg
  public/sourcegraph/sourcegraph-4.0-white.svg
  src/components/CoreFeatures.tsx
  src/components/CtaSection.tsx
  src/components/IntegrationsSection.tsx
  src/components/SelfHostedSection.tsx
  src/components/index.ts
  src/pages/home/_Banner.tsx
  src/pages/home/_Hero.tsx
  src/pages/home/_UseCases.tsx
  src/pages/home/index.tsx
Labels: team/content-platform, marketing-request

#5758 Sourcegraph 4 landing page updates for launch day
  package.json
  public/backgrounds/starship-launch-pills-large.svg
  src/pages/sourcegraph-4.tsx
  yarn.lock
Labels: team/content-platform

#5718 Pricing page - 4.0 updates
  src/components/Pricing/PricingPlan.tsx
  src/components/Pricing/PricingPlanFeature.tsx
  src/components/Pricing/data.ts
  src/components/Pricing/index.ts
  src/components/Pricing/interfaces.ts
  src/components/index.ts
  src/pages/pricing.tsx
  src/styles/_bootstrap-overrides.scss
  src/styles/globals.css
  src/styles/globals.scss
  tailwind.config.js
Labels: team/content-platform, marketing-request

#5775 4.0 countdown - Correct UTC launch time
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5776 Create 2022-03-28 archived version
  content/terms/archives/privacy/2022-03-28.md
Labels: legal

#5623 Sourcegraph 4.0 launch blogs
  content/blogposts/2022/code-intelligence-platform.md
  content/blogposts/2022/enterprise-cloud.md
  content/blogposts/2022/sourcegraph-4.0.md
  src/components/Figure.tsx
Labels: about-blog

#5765 4.0 Launch 🌌
  content/blogposts/2022/code-intelligence-platform.md
  content/blogposts/2022/enterprise-cloud.md
  content/blogposts/2022/sourcegraph-4.0.md
  package.json
  public/backgrounds/starship-launch-pills-large.svg
  public/sourcegraph/sourcegraph-4-starship.svg
  public/sourcegraph/sourcegraph-4.0-white.svg
  src/components/CaseStudies/CaseStudyLayout.tsx
  src/components/CaseStudies/NewCaseStudyLayout.tsx
  src/components/CoreFeatures.tsx
  src/components/CtaSection.tsx
  src/components/Figure.tsx
  src/components/IntegrationsSection.tsx
  src/components/Layout/Header/DesktopNav.tsx
  src/components/Layout/Header/MobileNav.tsx
  src/components/Pricing/PricingPlan.tsx
  src/components/Pricing/PricingPlanFeature.tsx
  src/components/Pricing/data.ts
  src/components/Pricing/index.ts
  src/components/Pricing/interfaces.ts
  src/components/ResourceList.tsx
  src/components/SelfHostedSection.tsx
  src/components/WhitePaperPage.tsx
  src/components/index.ts
  src/data/tracking.ts
  src/pages/batch-changes.tsx
  src/pages/better-dev-onboarding.tsx
  src/pages/blog/[...slug].tsx
  src/pages/case-studies/index.tsx
  src/pages/code-insights.tsx
  src/pages/code-search.tsx
  src/pages/demo.tsx
  src/pages/home/_Banner.tsx
  src/pages/home/_Hero.tsx
  src/pages/home/_UseCases.tsx
  src/pages/home/index.tsx
  src/pages/partner-podcast.tsx
  src/pages/pricing.tsx
  src/pages/resources.tsx
  src/pages/shift-left-the-good-parts.tsx
  src/pages/sourcegraph-4.tsx
  src/pages/support.tsx
  src/pages/use-cases/code-health.tsx
  src/pages/use-cases/code-reuse.tsx
  src/pages/use-cases/code-security.tsx
  src/pages/use-cases/incident-response.tsx
  src/pages/use-cases/index.tsx
  src/pages/use-cases/onboarding.tsx
  src/pages/videos/product-tour.tsx
  src/styles/_bootstrap-overrides.scss
  src/styles/globals.css
  src/styles/globals.scss
  tailwind.config.js
  yarn.lock
Labels: team/content-platform, sprint-rollover

#5782 4.0 landing page h1 width
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5784 Livestream timestamp
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5788 Removing extra 'on' enterprise cloud post
  content/blogposts/2022/enterprise-cloud.md
Labels: team/content-platform

#5790 Rm support page and redirect to contact page
  netlify.toml
  src/pages/support.tsx
Labels: team/content-platform, added-mid-sprint

#5786 4.0 post launch updates
  src/components/Badge.tsx
  src/components/IntegrationsSection.tsx
  src/components/ThreeUpText.tsx
  src/pages/home/_Banner.tsx
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5791 Add livestream video to 4.0 landing
  src/components/YouTube.tsx
  src/pages/sourcegraph-4.tsx
Labels: team/content-platform

#5804 Blog/ Remove nested code tag borders
  src/styles/templates/_PostTemplate.scss
Labels: team/content-platform, bug fix, tech debt

#5802 Navbar CTA update
  src/components/Layout/Header/DesktopNav.tsx
  src/components/Layout/Header/MobileNav.tsx
Labels: team/content-platform, marketing-request
