Repository sourcegraph/about, pull requests merged in 2023-04, with the labels that each got.

#6172 Add Contemplating Hype blog post
  content/blogposts/2023/contemplating-hype.md
Labels: about-blog

#6157 [SGM-6143] : fix tooltips in pricing page
  package.json
  pnpm-lock.yaml
  src/components/Pricing/PricingPlanFeature.tsx
  src/components/Tooltip.tsx
  src/components/index.ts
  src/pages/pricing.tsx
Labels: gitstart

#6146 Site name in Google search: Adding WebSite structured data
  src/pages/_document.tsx
Labels: gitstart

#6188 [SGM-6186]: Update Gartner page
  src/components/GatedResourceLayout.tsx
  src/components/Hero.tsx
  src/pages/2022-gartner-cool-vendors-in-software-engineering.tsx
Labels: gitstart

#6191 SGM-6190 - Bug: fix mobile on /cody
  src/pages/index.tsx
Labels: gitstart

#6193 Update community event section
  src/pages/community.tsx
Labels: marketing-request

#6197 SGM-6194 - Add tweets to /cody
  src/components/EmbedTweet.tsx
  src/pages/cody.tsx
Labels: gitstart

#6196 [SGM-6192]: Update /demo and /request-info pages
  public/backgrounds/background-contact.svg
  public/external-logos/redfin-logo.svg
  src/components/HubSpotForm.module.css
  src/pages/contact/[...slug].tsx
  src/pages/demo.tsx
Labels: gitstart

#6203 Update community.tsx
  src/pages/community.tsx
Labels: marketing

#6202 SGM-6201 - Fix Codebase-aware chat section on /cody
  src/pages/cody.tsx
Labels: gitstart

#6216 Update events section on community page
  src/pages/community.tsx
Labels: marketing-request

#6217 SGM-6204 - Big Code page
  public/backgrounds/big-code.svg
  public/rise-of-ai/14.svg
  public/rise-of-ai/72.svg
  public/rise-of-ai/73.svg
  public/rise-of-ai/illustration.png
  public/rise-of-ai/progress-bar1.svg
  public/rise-of-ai/progress-bar2.svg
  public/rise-of-ai/progress-bar3.svg
  public/rise-of-ai/rise-of-ai-og.png
  src/pages/big-code/BigCode.module.scss
  src/pages/big-code/big-code-in-ai-era.tsx
  src/pages/starship/Starship.module.scss
Labels: gitstart

#6223 [SGM-6220] - Add hello bar to homepage
  src/components/Banner.tsx
  src/components/Layout/Header/Header.tsx
Labels: gitstart
