Repository sourcegraph/about, pull requests merged in 2023-03, with the labels that each got.

#6025 Update security page
  netlify.toml
  src/components/Layout/Footer.tsx
  src/components/Layout/Layout.tsx
  src/components/Tabs.tsx
  src/pages/security.tsx
  src/styles/globals.css
Labels: enhancement, gitstart

#6059 Add Google search console verification
  public/google3900c75493388081.html
Labels: about-blog

#6052 SGM-6030 - Sourcegraph App page
  public/app/app-og.png
  public/app/batch-changes.svg
  public/icons/play-button.svg
  src/components/AppVideo.tsx
  src/components/Badge.tsx
  src/components/CodeSnippet.tsx
  src/components/Install/index.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Layout.tsx
  src/components/Tabs.tsx
  src/components/ThreeUpText.tsx
  src/lib/utils.ts
  src/pages/accessibility/index.tsx
  src/pages/app.tsx
  src/pages/batch-changes.tsx
  src/pages/code-insights.tsx
  src/pages/community.tsx
  src/pages/jobs.tsx
  src/pages/security.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: gitstart

#6053 [SGM-6033] - March 2023 Starship Page
  public/backgrounds/background-launch-pill.svg
  public/backgrounds/foreground-launch-pill.svg
  public/backgrounds/midground-launch-pill.svg
  public/starship/cody-illustration.svg
  public/starship/davidsacks.png
  public/starship/ericabrescia.png
  public/starship/launch.svg
  public/starship/mid-page-launch-pills.svg
  public/starship/own-illustration.svg
  public/starship/sentinel-illustration.svg
  public/starship/simonmarlow.png
  public/starship/starship-app.svg
  public/starship/starship-blur.svg
  public/starship/starship_og.png
  src/components/CustomerLogos.tsx
  src/components/GetStartedButton.tsx
  src/components/Layout/Footer.tsx
  src/components/Starship/CountDown.tsx
  src/components/Starship/FeatureUser.tsx
  src/components/Starship/TwoColWithImage.tsx
  src/components/Starship/TwoRowWithImage.tsx
  src/components/cta/StarshipPageCallToAction.tsx
  src/components/cta/TrySourcegraphForFreeButton.tsx
  src/components/index.ts
  src/pages/_document.tsx
  src/pages/starship/Starship.module.scss
  src/pages/starship/index.tsx
  src/styles/globals.css
  src/util/remainingTime.ts
  tailwind.config.js
Labels: gitstart

#6026 Changes to the Sourcegraph release cadence
  content/blogposts/2023/changes-to-the-sourcegraph-release-cadence.md
Labels: about-blog

#6047 Create code ownership vision blog
  content/blogposts/2023/our-vision-for-code-ownership.md
Labels: about-blog

#6072 Remove meta data
  content/blogposts/2023/pydantic.md
Labels: about-blog

#6076 feat: Cody page Implementation
  public/cody/cody-og.png
  public/cody/cody.svg
  src/pages/cody.tsx
  src/styles/globals.css
Labels: gitstart

#6077 feat: Sourcegraph Own page implementation
  public/check-circle.svg
  public/light.svg
  public/own/og-own.png
  public/own/own-illustration.svg
  src/components/Own/FeatureRoadMap.tsx
  src/components/Own/index.ts
  src/components/cta/StarshipPageCallToAction.tsx
  src/components/index.ts
  src/pages/app.tsx
  src/pages/own.tsx
  src/pages/starship/index.tsx
  src/styles/globals.css
Labels: gitstart

#6091 SGM-6057 - Homepage updates
  netlify.toml
  public/home/Frame 670.svg
  public/home/background.svg
  public/home/banner.png
  public/home/code_intelligence.png
  public/home/fix.png
  public/home/search.png
  public/linux-icon.svg
  public/testimonies/bryce-kalow-2.svg
  public/testimonies/justin-phillip.svg
  public/testimonies/ronnie-magatti.svg
  src/components/Badge.tsx
  src/components/CustomerLogos.tsx
  src/components/GetStartedButton.tsx
  src/components/IntegrationsSection.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/NavItems.tsx
  src/components/Layout/Layout.tsx
  src/components/Starship/CountDown.tsx
  src/components/Tabs.tsx
  src/components/cta/CallToActionContentSection.tsx
  src/components/cta/TrySourcegraphForFreeButton.tsx
  src/pages/accelerate-dev-onboarding.tsx
  src/pages/code-intelligence-platform.tsx
  src/pages/fixing-vulnerabilities.tsx
  src/pages/get-started.tsx
  src/pages/index.tsx
  src/pages/pricing.tsx
  src/pages/webinars/code-insights-turning-your-metrics-into-action.tsx
  src/styles/getStarted.module.scss
  src/styles/globals.css
  tailwind.config.js
Labels: gitstart

#6094 Add Download button to /app
  src/pages/app.tsx
Labels: gitstart

#6122 [SGM-6109] : Adjustments to the Pricing page
  src/components/Pricing/PricingPlan.tsx
  src/pages/pricing.tsx
Labels: gitstart

#6126 Add podcast 3.8
  content/podcast/3.8.md
Labels: podcast

#6133 Fix: Update signup links
  content/blogposts/2022/code-intelligence-platform.md
  content/blogposts/2022/enterprise-cloud.md
  content/blogposts/2022/sourcegraph-4.0.md
Labels: gitstart
