Repository sourcegraph/about, pull requests merged in 2023-06, with the labels that each got.

#6284 Remove DigiTech Forum 2023 from community events
  src/pages/community.tsx
Labels: marketing

#6297 Update events section
  src/pages/community.tsx
Labels: marketing

#6307 Update App download url
  src/data/downloads.ts
Labels: bug fix

#6291 [SGM-6281] - Research request: Improve Core Web Vitals
  package.json
  pnpm-lock.yaml
  src/components/Blog/PostListItem.tsx
  src/components/Carousels/VideoCarousel.tsx
  src/components/CaseStudies/CaseStudyLayout.tsx
  src/components/CoreFeatures.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/lib/api.ts
  src/lib/utils.ts
  src/pages/index.tsx
  src/pages/use-cases/index.tsx
Labels: gitstart

#6306 [SGM-6298] - Host PDF in the about site
  public/guide/sourcegraph-for-platform-engineering.pdf
  public/whitepaper/cody-context-architecture.pdf
  public/whitepaper/how-sourcegraph-ai-platform-powers-cody.pdf
Labels: gitstart

#6316 SGM-6315 - Reupload PDFs
  public/whitepaper/cody-context-architecture.pdf
  public/whitepaper/how-sourcegraph-ai-platform-powers-cody.pdf
Labels: gitstart

#6301 SGM-6285 - Add search bar to /resources
  public/big-code.png
  src/components/AppVideo.tsx
  src/components/Badge.tsx
  src/components/CodyVideo.tsx
  src/components/CoreFeatures.tsx
  src/components/DemoVideo.tsx
  src/components/DownloadLink.tsx
  src/components/Layout/Header/NavItems.tsx
  src/components/Resources/Filters.tsx
  src/components/Resources/ResourceCard.tsx
  src/components/Resources/index.ts
  src/components/Resources/resourceItems.ts
  src/components/Resources/useFilters.ts
  src/components/Video.tsx
  src/components/cta/EmailAuth.tsx
  src/components/cta/ExternalsAuth.tsx
  src/components/index.ts
  src/hooks/eventLogger.ts
  src/pages/own.tsx
  src/pages/resources.tsx
  src/styles/globals.css
  src/util/logAuthPopoverEvent.ts
  tailwind.config.js
Labels: gitstart

#6259 [SGM-6255] : Update Big Code mobile background
  src/pages/app.tsx
  src/pages/big-code/big-code-in-ai-era.tsx
  src/styles/globals.css
Labels: gitstart

#6317 Cody keyboard giveaway
  content/blogposts/2023/cody-mechanical-keyboard-giveaway.md
Labels: about-blog

#6355 Update Twitter link
  content/blogposts/2023/cody-mechanical-keyboard-giveaway.md
Labels: about-blog

#6361 Fix typo: Momal try 3
  content/blogposts/2023/whats-new-with-cody-5.1.md
Labels: about-blog
