Repository sourcegraph/about, pull requests merged in 2023-07, with the labels that each got.

#6393 [SGM-6389] - Updates to Cody page (we're working to bring you Cody section)
  public/cody/cody-color-icon.png
  public/cody/down-arrow.svg
  public/cody/right-arrow.svg
  src/components/CodyFeatureCard.tsx
  src/pages/cody.tsx
  src/styles/globals.css
Labels: gitstart

#6397 SGM-6392 - Add Pixels for tracking to about
  src/components/cta/ExternalsAuth.tsx
  src/lib/utils.ts
  src/pages/_document.tsx
Labels: gitstart

#6396 SGM-6390 - Fix tweets on homepage and /cody
  next.config.js
  package.json
  pnpm-lock.yaml
  src/components/EmbedTweet.tsx
  src/components/index.ts
  src/pages/cody.tsx
  src/pages/constants.ts
  src/pages/index.tsx
Labels: gitstart

#6398 Update view the code link
  content/blogposts/2023/open-sourcing-cody.md
Labels: about-blog

#6400 Update Tweets on /cody page
  src/pages/constants.ts
Labels: marketing

#6433 [SGM-6420] : Update /about page to include Chris
  public/staff/avatar-chris.jpg
  public/staff/avatar-greg.jpg
  src/components/LeadershipSection.tsx
Labels: gitstart
