Repository sourcegraph/about, pull requests merged in 2023-01, with the labels that each got.

#5944 Adjust Cloud nav & footer bg
  src/components/Layout/Header/index.tsx
  src/pages/cloud.tsx
  src/styles/components/_Header.scss
  src/styles/globals.css
  tailwind.config.js
Labels: team/growth-marketing

#5959 Update title, move YouTube video down
  content/blogposts/2022/building-the-foundation-of-code-search.md
Labels: about-blog

#5948 Fix typo on Code Insights landing page
  src/components/CodeInsights/mock-data.tsx
  src/pages/code-insights.tsx
Labels: medium priority
